### ISSUE TITLE
bug: space in sort key expression in query function

### ISSUE THREAD

**Issue by sinha-manish** [AbhijeetSingla/simple-dynamo-utils#2]
in `parameters.js` the expression should include spaces around the operator
- currently
 ` 'AND'.concat(...)`
- should be
 ` ' AND '.concat(...)`

**Comment by AbhijeetSingla** [comment]
fixed in [pull request #3](https://github.com/AbhijeetSingla/simple-dynamo-utils/pull/3)

Thanks :)
